version: "3.1"

services:
  ourboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${HOST_PORT}:1337
    environment:
      # https://github.com/raimohanska/ourboard#hosting
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_DATABASE}"
      WS_HOST_DEFAULT: ${HOST_IP}:${HOST_PORT}
      WS_HOST_LOCAL: ${HOST_IP}:${HOST_PORT}
      WS_PROTOCOL: ws
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13
    restart: always
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "$PWD/container_data/postgres/13/data/:/var/lib/postgresql/data:Z"
    healthcheck:
      test:
        [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_DATABASE}" ]
      interval: 5s
      retries: 20
  pgweb:
    image: sosedoff/pgweb:0.14.0
    environment:
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_DATABASE}?sslmode=disable"
    ports:
      - 8081:8081
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nc", "-vz", "localhost", "8081" ]
      interval: 5s
